# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orders.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'orders.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0corders.proto\x12\torders.v1\"7\n\x0e\x43reateOrderReq\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\x12\x10\n\x08item_ids\x18\x02 \x03(\t\"\"\n\x0e\x43reateOrderRes\x12\x10\n\x08order_id\x18\x01 \x01(\t\"#\n\x0fStreamStatusReq\x12\x10\n\x08order_id\x18\x01 \x01(\t\")\n\x0bStatusEvent\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\n\n\x02ts\x18\x02 \x01(\x03\" \n\x04Note\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\n\n\x02ts\x18\x02 \x01(\x03\"\x1e\n\rUploadSummary\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\"1\n\x07\x43hatMsg\x12\x0c\n\x04\x66rom\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\n\n\x02ts\x18\x03 \x01(\x03\x32\x8c\x02\n\x0cOrderService\x12@\n\x06\x43reate\x12\x19.orders.v1.CreateOrderReq\x1a\x19.orders.v1.CreateOrderRes\"\x00\x12\x46\n\x0cStreamStatus\x12\x1a.orders.v1.StreamStatusReq\x1a\x16.orders.v1.StatusEvent\"\x00\x30\x01\x12<\n\x0bUploadNotes\x12\x0f.orders.v1.Note\x1a\x18.orders.v1.UploadSummary\"\x00(\x01\x12\x34\n\x04\x43hat\x12\x12.orders.v1.ChatMsg\x1a\x12.orders.v1.ChatMsg\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orders_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEORDERREQ']._serialized_start=27
  _globals['_CREATEORDERREQ']._serialized_end=82
  _globals['_CREATEORDERRES']._serialized_start=84
  _globals['_CREATEORDERRES']._serialized_end=118
  _globals['_STREAMSTATUSREQ']._serialized_start=120
  _globals['_STREAMSTATUSREQ']._serialized_end=155
  _globals['_STATUSEVENT']._serialized_start=157
  _globals['_STATUSEVENT']._serialized_end=198
  _globals['_NOTE']._serialized_start=200
  _globals['_NOTE']._serialized_end=232
  _globals['_UPLOADSUMMARY']._serialized_start=234
  _globals['_UPLOADSUMMARY']._serialized_end=264
  _globals['_CHATMSG']._serialized_start=266
  _globals['_CHATMSG']._serialized_end=315
  _globals['_ORDERSERVICE']._serialized_start=318
  _globals['_ORDERSERVICE']._serialized_end=586
# @@protoc_insertion_point(module_scope)
